-- ============================================================
-- Migration 003 — Structured RAG pipeline + Voyage AI (vector 1024)
-- Run in Supabase SQL Editor
-- ============================================================

-- ── 1. documents table ────────────────────────────────────────
-- One row per uploaded textbook
CREATE TABLE IF NOT EXISTS public.documents (
  id              bigint generated by default as identity primary key,
  title           text not null,
  subject         text not null,
  grade           text not null,
  language        text not null,
  curriculum_year text default '2023',
  file_name       text not null,
  uploaded_by     text default 'Admin',
  created_at      timestamp with time zone default timezone('utc'::text, now()) not null
);

ALTER TABLE public.documents ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authenticated users can read documents"
  ON public.documents FOR SELECT TO authenticated USING (true);

CREATE POLICY "Admins can manage documents"
  ON public.documents FOR ALL TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.profiles
      WHERE profiles.id = auth.uid() AND profiles.role = 'admin'
    )
  );

-- ── 2. chapters table ─────────────────────────────────────────
-- One row per chapter per document
CREATE TABLE IF NOT EXISTS public.chapters (
  id             bigint generated by default as identity primary key,
  document_id    bigint references public.documents on delete cascade not null,
  chapter_number int not null,
  title          text not null,
  page_start     int default 0,
  created_at     timestamp with time zone default timezone('utc'::text, now()) not null
);

ALTER TABLE public.chapters ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authenticated users can read chapters"
  ON public.chapters FOR SELECT TO authenticated USING (true);

CREATE POLICY "Admins can manage chapters"
  ON public.chapters FOR ALL TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.profiles
      WHERE profiles.id = auth.uid() AND profiles.role = 'admin'
    )
  );

-- ── 3. Drop old embedding column + add new vector(1024) ───────
-- Must drop the HNSW index first, then the column, then recreate
DROP INDEX IF EXISTS public.curriculum_chunks_embedding_hnsw;
DROP INDEX IF EXISTS public.curriculum_chunks_source_chunk_idx;

ALTER TABLE public.curriculum_chunks DROP COLUMN IF EXISTS embedding;
ALTER TABLE public.curriculum_chunks ADD COLUMN embedding vector(1024);

-- ── 4. Add structured metadata columns to curriculum_chunks ──
ALTER TABLE public.curriculum_chunks
  ADD COLUMN IF NOT EXISTS document_id    bigint references public.documents on delete cascade,
  ADD COLUMN IF NOT EXISTS chapter_id     bigint references public.chapters on delete set null,
  ADD COLUMN IF NOT EXISTS chapter        text,
  ADD COLUMN IF NOT EXISTS section        text,
  ADD COLUMN IF NOT EXISTS page_number    int default 0,
  ADD COLUMN IF NOT EXISTS chunk_type     text default 'text'
    CHECK (chunk_type IN ('text','definition','equation','formula','table','example','question','answer','code','passage'));

-- ── 5. Rebuild indexes ────────────────────────────────────────
-- HNSW for fast similarity search (build after bulk load)
CREATE INDEX IF NOT EXISTS curriculum_chunks_embedding_hnsw
  ON public.curriculum_chunks
  USING hnsw (embedding vector_cosine_ops);

-- Composite index for neighbor expansion queries
CREATE INDEX IF NOT EXISTS curriculum_chunks_source_chunk_idx
  ON public.curriculum_chunks (source_document, chunk_index);

-- Index for document-based queries
CREATE INDEX IF NOT EXISTS curriculum_chunks_document_idx
  ON public.curriculum_chunks (document_id, chunk_index);

-- ── 6. Update match_chunks to return new metadata + vector(1024)
DROP FUNCTION IF EXISTS public.match_chunks(vector, float, int, text, text, text);

CREATE OR REPLACE FUNCTION public.match_chunks (
  query_embedding  vector(1024),
  match_threshold  float,
  match_count      int,
  filter_subject   text,
  filter_grade     text,
  filter_language  text
) RETURNS TABLE (
  id              bigint,
  subject         text,
  topic           text,
  grade           text,
  language        text,
  source_document text,
  content         text,
  chunk_index     integer,
  chunk_type      text,
  chapter         text,
  section         text,
  page_number     integer,
  similarity      float
)
LANGUAGE plpgsql
AS $$
BEGIN
  RETURN QUERY
  SELECT
    cc.id,
    cc.subject,
    cc.topic,
    cc.grade,
    cc.language,
    cc.source_document,
    cc.content,
    cc.chunk_index,
    cc.chunk_type,
    cc.chapter,
    cc.section,
    cc.page_number,
    1 - (cc.embedding <=> query_embedding) AS similarity
  FROM public.curriculum_chunks cc
  WHERE cc.subject       = filter_subject
    AND cc.grade         = filter_grade
    AND cc.language      = filter_language
    AND 1 - (cc.embedding <=> query_embedding) > match_threshold
  ORDER BY cc.embedding <=> query_embedding
  LIMIT match_count;
END;
$$;

-- ── 7. Update schema.sql reference comment ───────────────────
-- Supabase triggers rebuild of schema cache automatically
NOTIFY pgrst, 'reload schema';
