-- ============================================================
-- Migration 001 — Apply new columns and tables
-- Run this in Supabase SQL Editor
-- Safe to run on existing data — uses IF NOT EXISTS / ADD COLUMN IF NOT EXISTS
-- ============================================================

-- 1. profiles: add grade_taught for teachers
ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS grade_taught text;

-- 2. tutor_messages: add sources and out_of_scope
ALTER TABLE public.tutor_messages
  ADD COLUMN IF NOT EXISTS sources jsonb,
  ADD COLUMN IF NOT EXISTS out_of_scope boolean DEFAULT false;

-- 3. teacher_assignments table
CREATE TABLE IF NOT EXISTS public.teacher_assignments (
  id              bigint generated by default as identity primary key,
  exam_id         bigint references public.exams on delete cascade not null,
  teacher_id      uuid references auth.users on delete cascade not null,
  title           text not null,
  assignment_type text not null check (assignment_type in ('quiz', 'homework', 'assignment')),
  target_grade    text not null,
  due_date        timestamp with time zone not null,
  published       boolean not null default false,
  published_at    timestamp with time zone,
  created_at      timestamp with time zone default timezone('utc'::text, now()) not null
);

ALTER TABLE public.teacher_assignments ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE tablename = 'teacher_assignments' AND policyname = 'Teachers can manage their own assignments'
  ) THEN
    CREATE POLICY "Teachers can manage their own assignments"
      ON public.teacher_assignments FOR ALL
      TO authenticated
      USING (auth.uid() = teacher_id);
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE tablename = 'teacher_assignments' AND policyname = 'Students can view published assignments for their grade'
  ) THEN
    CREATE POLICY "Students can view published assignments for their grade"
      ON public.teacher_assignments FOR SELECT
      TO authenticated
      USING (
        published = true
        AND EXISTS (
          SELECT 1 FROM public.profiles
          WHERE profiles.id = auth.uid()
            AND profiles.grade = target_grade
            AND profiles.role = 'student'
        )
      );
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE tablename = 'teacher_assignments' AND policyname = 'Admins can manage all assignments'
  ) THEN
    CREATE POLICY "Admins can manage all assignments"
      ON public.teacher_assignments FOR ALL
      TO authenticated
      USING (
        EXISTS (
          SELECT 1 FROM public.profiles
          WHERE profiles.id = auth.uid() AND profiles.role = 'admin'
        )
      );
  END IF;
END $$;

-- 4. assignment_submissions table
CREATE TABLE IF NOT EXISTS public.assignment_submissions (
  id               bigint generated by default as identity primary key,
  assignment_id    bigint references public.teacher_assignments on delete cascade not null,
  exam_id          bigint references public.exams on delete cascade not null,
  student_id       uuid references auth.users on delete cascade not null,
  answers          jsonb not null,
  raw_score        float,
  teacher_score    float,
  teacher_feedback text,
  graded           boolean not null default false,
  submitted_at     timestamp with time zone default timezone('utc'::text, now()) not null,
  graded_at        timestamp with time zone
);

ALTER TABLE public.assignment_submissions ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE tablename = 'assignment_submissions' AND policyname = 'Students can manage their own submissions'
  ) THEN
    CREATE POLICY "Students can manage their own submissions"
      ON public.assignment_submissions FOR ALL
      TO authenticated
      USING (auth.uid() = student_id);
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE tablename = 'assignment_submissions' AND policyname = 'Teachers can read and grade submissions for their assignments'
  ) THEN
    CREATE POLICY "Teachers can read and grade submissions for their assignments"
      ON public.assignment_submissions FOR ALL
      TO authenticated
      USING (
        EXISTS (
          SELECT 1 FROM public.teacher_assignments ta
          WHERE ta.id = assignment_id AND ta.teacher_id = auth.uid()
        )
      );
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE tablename = 'assignment_submissions' AND policyname = 'Admins can manage all submissions'
  ) THEN
    CREATE POLICY "Admins can manage all submissions"
      ON public.assignment_submissions FOR ALL
      TO authenticated
      USING (
        EXISTS (
          SELECT 1 FROM public.profiles
          WHERE profiles.id = auth.uid() AND profiles.role = 'admin'
        )
      );
  END IF;
END $$;

-- 5. Update handle_new_user trigger to include grade_taught
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.profiles (id, name, role, grade, grade_taught, language)
  VALUES (
    new.id,
    COALESCE(new.raw_user_meta_data->>'name', 'New User'),
    COALESCE(new.raw_user_meta_data->>'role', 'student'),
    new.raw_user_meta_data->>'grade',
    new.raw_user_meta_data->>'grade_taught',
    COALESCE(new.raw_user_meta_data->>'language', 'English')
  );
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 6. match_chunks function — ensure it exists with correct signature
CREATE OR REPLACE FUNCTION public.match_chunks (
  query_embedding  vector(1536),
  match_threshold  float,
  match_count      int,
  filter_subject   text,
  filter_grade     text,
  filter_language  text
) RETURNS TABLE (
  id              bigint,
  subject         text,
  topic           text,
  grade           text,
  language        text,
  source_document text,
  content         text,
  similarity      float
)
LANGUAGE plpgsql
AS $$
BEGIN
  RETURN QUERY
  SELECT
    cc.id,
    cc.subject,
    cc.topic,
    cc.grade,
    cc.language,
    cc.source_document,
    cc.content,
    1 - (cc.embedding <=> query_embedding) AS similarity
  FROM public.curriculum_chunks cc
  WHERE cc.subject       = filter_subject
    AND cc.grade         = filter_grade
    AND cc.language      = filter_language
    AND 1 - (cc.embedding <=> query_embedding) > match_threshold
  ORDER BY cc.embedding <=> query_embedding
  LIMIT match_count;
END;
$$;
