-- ============================================================
-- I-PASS-A AI PLATFORM
-- COMPLETE SUPABASE DATABASE SCHEMA
-- ============================================================

-- ============================================================
-- 1. ENABLE EXTENSIONS
-- ============================================================

CREATE EXTENSION IF NOT EXISTS vector;


-- ============================================================
-- 2. CLEAN OLD I-PASS-A TABLES
--    WARNING: Deletes existing application data.
-- ============================================================

DROP TABLE IF EXISTS public.tutor_messages CASCADE;
DROP TABLE IF EXISTS public.tutor_sessions CASCADE;
DROP TABLE IF EXISTS public.exam_attempts CASCADE;
DROP TABLE IF EXISTS public.exams CASCADE;
DROP TABLE IF EXISTS public.curriculum_chunks CASCADE;
DROP TABLE IF EXISTS public.profiles CASCADE;

DROP FUNCTION IF EXISTS public.match_chunks(
    vector,
    float,
    int,
    text,
    text,
    text
);

DROP FUNCTION IF EXISTS public.handle_new_user() CASCADE;


-- ============================================================
-- 3. PROFILES
--    Connects Supabase Auth users to application profiles.
-- ============================================================

CREATE TABLE public.profiles (
    id UUID
        REFERENCES auth.users(id)
        ON DELETE CASCADE
        PRIMARY KEY,

    name TEXT NOT NULL,

    role TEXT NOT NULL
        CHECK (role IN ('student', 'teacher', 'admin')),

    grade TEXT,

    language TEXT NOT NULL DEFAULT 'English',

    created_at TIMESTAMPTZ
        NOT NULL DEFAULT timezone('utc'::text, now())
);


-- ============================================================
-- 4. ENABLE RLS ON PROFILES
-- ============================================================

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;


-- Users can read their own profile.
CREATE POLICY "Users can read their own profile"
ON public.profiles
FOR SELECT
TO authenticated
USING (
    auth.uid() = id
);


-- Admins and teachers can read profiles.
CREATE POLICY "Admins and teachers can read profiles"
ON public.profiles
FOR SELECT
TO authenticated
USING (
    EXISTS (
        SELECT 1
        FROM public.profiles p
        WHERE p.id = auth.uid()
        AND p.role IN ('admin', 'teacher')
    )
);


-- Users can update their own profile.
CREATE POLICY "Users can update their own profile"
ON public.profiles
FOR UPDATE
TO authenticated
USING (
    auth.uid() = id
)
WITH CHECK (
    auth.uid() = id
);


-- ============================================================
-- 5. AUTOMATIC PROFILE CREATION
-- ============================================================

CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    user_role TEXT;
BEGIN

    -- Convert frontend role names to database roles.
    user_role :=
        CASE
            WHEN LOWER(
                COALESCE(
                    NEW.raw_user_meta_data ->> 'role',
                    'student'
                )
            ) IN (
                'admin',
                'administrator',
                'content administrator'
            )
            THEN 'admin'

            WHEN LOWER(
                COALESCE(
                    NEW.raw_user_meta_data ->> 'role',
                    'student'
                )
            ) IN (
                'teacher',
                'educator'
            )
            THEN 'teacher'

            ELSE 'student'
        END;


    INSERT INTO public.profiles (
        id,
        name,
        role,
        grade,
        language
    )
    VALUES (
        NEW.id,

        COALESCE(
            NEW.raw_user_meta_data ->> 'name',
            'New User'
        ),

        user_role,

        NEW.raw_user_meta_data ->> 'grade',

        COALESCE(
            NEW.raw_user_meta_data ->> 'language',
            'English'
        )
    );

    RETURN NEW;

END;
$$;


-- ============================================================
-- 6. CREATE AUTH USER TRIGGER
-- ============================================================

CREATE TRIGGER on_auth_user_created
AFTER INSERT
ON auth.users
FOR EACH ROW
EXECUTE FUNCTION public.handle_new_user();


-- ============================================================
-- 7. CURRICULUM CHUNKS
--    Used for AI/RAG curriculum search.
-- ============================================================

CREATE TABLE public.curriculum_chunks (
    id BIGINT
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    subject TEXT NOT NULL,

    topic TEXT NOT NULL,

    grade TEXT NOT NULL,

    language TEXT NOT NULL,

    source_document TEXT NOT NULL,

    content TEXT NOT NULL,

    embedding VECTOR(1536),

    version INT NOT NULL DEFAULT 1,

    uploaded_by TEXT DEFAULT 'System',

    created_at TIMESTAMPTZ
        NOT NULL DEFAULT timezone('utc'::text, now())
);


-- ============================================================
-- 8. CURRICULUM RLS
-- ============================================================

ALTER TABLE public.curriculum_chunks ENABLE ROW LEVEL SECURITY;


-- Authenticated users can read curriculum.
CREATE POLICY "Authenticated users can read curriculum"
ON public.curriculum_chunks
FOR SELECT
TO authenticated
USING (true);


-- Admins and teachers can insert curriculum.
CREATE POLICY "Admins and teachers can insert curriculum"
ON public.curriculum_chunks
FOR INSERT
TO authenticated
WITH CHECK (
    EXISTS (
        SELECT 1
        FROM public.profiles
        WHERE profiles.id = auth.uid()
        AND profiles.role IN ('admin', 'teacher')
    )
);


-- Admins and teachers can update curriculum.
CREATE POLICY "Admins and teachers can update curriculum"
ON public.curriculum_chunks
FOR UPDATE
TO authenticated
USING (
    EXISTS (
        SELECT 1
        FROM public.profiles
        WHERE profiles.id = auth.uid()
        AND profiles.role IN ('admin', 'teacher')
    )
)
WITH CHECK (
    EXISTS (
        SELECT 1
        FROM public.profiles
        WHERE profiles.id = auth.uid()
        AND profiles.role IN ('admin', 'teacher')
    )
);


-- Admins and teachers can delete curriculum.
CREATE POLICY "Admins and teachers can delete curriculum"
ON public.curriculum_chunks
FOR DELETE
TO authenticated
USING (
    EXISTS (
        SELECT 1
        FROM public.profiles
        WHERE profiles.id = auth.uid()
        AND profiles.role IN ('admin', 'teacher')
    )
);


-- ============================================================
-- 9. VECTOR SEARCH FUNCTION
-- ============================================================

CREATE OR REPLACE FUNCTION public.match_chunks (
    query_embedding VECTOR(1536),
    match_threshold FLOAT,
    match_count INT,
    filter_subject TEXT,
    filter_grade TEXT,
    filter_language TEXT
)
RETURNS TABLE (
    id BIGINT,
    subject TEXT,
    topic TEXT,
    grade TEXT,
    language TEXT,
    source_document TEXT,
    content TEXT,
    similarity FLOAT
)
LANGUAGE plpgsql
AS $$
BEGIN

    RETURN QUERY

    SELECT
        cc.id,
        cc.subject,
        cc.topic,
        cc.grade,
        cc.language,
        cc.source_document,
        cc.content,

        1 - (
            cc.embedding <=> query_embedding
        ) AS similarity

    FROM public.curriculum_chunks cc

    WHERE cc.subject = filter_subject

    AND cc.grade = filter_grade

    AND cc.language = filter_language

    AND cc.embedding IS NOT NULL

    AND 1 - (
        cc.embedding <=> query_embedding
    ) > match_threshold

    ORDER BY
        cc.embedding <=> query_embedding

    LIMIT match_count;

END;
$$;


-- ============================================================
-- 10. TUTOR SESSIONS
-- ============================================================

CREATE TABLE public.tutor_sessions (
    id BIGINT
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    user_id UUID
        REFERENCES auth.users(id)
        ON DELETE CASCADE
        NOT NULL,

    subject TEXT NOT NULL,

    started_at TIMESTAMPTZ
        NOT NULL DEFAULT timezone('utc'::text, now())
);


-- ============================================================
-- 11. TUTOR SESSION RLS
-- ============================================================

ALTER TABLE public.tutor_sessions ENABLE ROW LEVEL SECURITY;


CREATE POLICY "Users can read their own tutor sessions"
ON public.tutor_sessions
FOR SELECT
TO authenticated
USING (
    auth.uid() = user_id
);


CREATE POLICY "Users can create their own tutor sessions"
ON public.tutor_sessions
FOR INSERT
TO authenticated
WITH CHECK (
    auth.uid() = user_id
);


CREATE POLICY "Users can update their own tutor sessions"
ON public.tutor_sessions
FOR UPDATE
TO authenticated
USING (
    auth.uid() = user_id
)
WITH CHECK (
    auth.uid() = user_id
);


CREATE POLICY "Users can delete their own tutor sessions"
ON public.tutor_sessions
FOR DELETE
TO authenticated
USING (
    auth.uid() = user_id
);


-- ============================================================
-- 12. TUTOR MESSAGES
-- ============================================================

CREATE TABLE public.tutor_messages (
    id BIGINT
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    session_id BIGINT
        REFERENCES public.tutor_sessions(id)
        ON DELETE CASCADE
        NOT NULL,

    sender TEXT NOT NULL
        CHECK (sender IN ('student', 'tutor')),

    content TEXT NOT NULL,

    timestamp TIMESTAMPTZ
        NOT NULL DEFAULT timezone('utc'::text, now())
);


-- ============================================================
-- 13. TUTOR MESSAGE RLS
-- ============================================================

ALTER TABLE public.tutor_messages ENABLE ROW LEVEL SECURITY;


CREATE POLICY "Users can read their own tutor messages"
ON public.tutor_messages
FOR SELECT
TO authenticated
USING (
    EXISTS (
        SELECT 1
        FROM public.tutor_sessions
        WHERE tutor_sessions.id = session_id
        AND tutor_sessions.user_id = auth.uid()
    )
);


CREATE POLICY "Users can create their own tutor messages"
ON public.tutor_messages
FOR INSERT
TO authenticated
WITH CHECK (
    EXISTS (
        SELECT 1
        FROM public.tutor_sessions
        WHERE tutor_sessions.id = session_id
        AND tutor_sessions.user_id = auth.uid()
    )
);


CREATE POLICY "Users can update their own tutor messages"
ON public.tutor_messages
FOR UPDATE
TO authenticated
USING (
    EXISTS (
        SELECT 1
        FROM public.tutor_sessions
        WHERE tutor_sessions.id = session_id
        AND tutor_sessions.user_id = auth.uid()
    )
)
WITH CHECK (
    EXISTS (
        SELECT 1
        FROM public.tutor_sessions
        WHERE tutor_sessions.id = session_id
        AND tutor_sessions.user_id = auth.uid()
    )
);


CREATE POLICY "Users can delete their own tutor messages"
ON public.tutor_messages
FOR DELETE
TO authenticated
USING (
    EXISTS (
        SELECT 1
        FROM public.tutor_sessions
        WHERE tutor_sessions.id = session_id
        AND tutor_sessions.user_id = auth.uid()
    )
);


-- ============================================================
-- 14. EXAMS
-- ============================================================

CREATE TABLE public.exams (
    id BIGINT
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    subject TEXT NOT NULL,

    topic TEXT NOT NULL,

    difficulty TEXT NOT NULL,

    grade TEXT NOT NULL,

    created_by UUID
        REFERENCES auth.users(id)
        ON DELETE SET NULL,

    questions JSONB NOT NULL,

    answer_key JSONB NOT NULL,

    created_at TIMESTAMPTZ
        NOT NULL DEFAULT timezone('utc'::text, now())
);


-- ============================================================
-- 15. EXAM RLS
-- ============================================================

ALTER TABLE public.exams ENABLE ROW LEVEL SECURITY;


-- Authenticated users can read exams.
CREATE POLICY "Authenticated users can read exams"
ON public.exams
FOR SELECT
TO authenticated
USING (true);


-- Teachers/admins can create exams.
CREATE POLICY "Teachers and admins can create exams"
ON public.exams
FOR INSERT
TO authenticated
WITH CHECK (
    EXISTS (
        SELECT 1
        FROM public.profiles
        WHERE profiles.id = auth.uid()
        AND profiles.role IN ('admin', 'teacher')
    )
);


-- Teachers/admins can update exams.
CREATE POLICY "Teachers and admins can update exams"
ON public.exams
FOR UPDATE
TO authenticated
USING (
    EXISTS (
        SELECT 1
        FROM public.profiles
        WHERE profiles.id = auth.uid()
        AND profiles.role IN ('admin', 'teacher')
    )
)
WITH CHECK (
    EXISTS (
        SELECT 1
        FROM public.profiles
        WHERE profiles.id = auth.uid()
        AND profiles.role IN ('admin', 'teacher')
    )
);


-- Teachers/admins can delete exams.
CREATE POLICY "Teachers and admins can delete exams"
ON public.exams
FOR DELETE
TO authenticated
USING (
    EXISTS (
        SELECT 1
        FROM public.profiles
        WHERE profiles.id = auth.uid()
        AND profiles.role IN ('admin', 'teacher')
    )
);


-- ============================================================
-- 16. EXAM ATTEMPTS
-- ============================================================

CREATE TABLE public.exam_attempts (
    id BIGINT
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    exam_id BIGINT
        REFERENCES public.exams(id)
        ON DELETE CASCADE
        NOT NULL,

    student_id UUID
        REFERENCES auth.users(id)
        ON DELETE CASCADE
        NOT NULL,

    answers JSONB NOT NULL,

    score FLOAT NOT NULL,

    submitted_at TIMESTAMPTZ
        NOT NULL DEFAULT timezone('utc'::text, now())
);


-- ============================================================
-- 17. EXAM ATTEMPTS RLS
-- ============================================================

ALTER TABLE public.exam_attempts ENABLE ROW LEVEL SECURITY;


-- Students can read their own attempts.
CREATE POLICY "Students can read their own exam attempts"
ON public.exam_attempts
FOR SELECT
TO authenticated
USING (
    auth.uid() = student_id
);


-- Students can create their own attempts.
CREATE POLICY "Students can create their own exam attempts"
ON public.exam_attempts
FOR INSERT
TO authenticated
WITH CHECK (
    auth.uid() = student_id
);


-- Students can update their own attempts.
CREATE POLICY "Students can update their own exam attempts"
ON public.exam_attempts
FOR UPDATE
TO authenticated
USING (
    auth.uid() = student_id
)
WITH CHECK (
    auth.uid() = student_id
);


-- Students can delete their own attempts.
CREATE POLICY "Students can delete their own exam attempts"
ON public.exam_attempts
FOR DELETE
TO authenticated
USING (
    auth.uid() = student_id
);


-- Teachers/admins can read all attempts.
CREATE POLICY "Teachers and admins can read exam attempts"
ON public.exam_attempts
FOR SELECT
TO authenticated
USING (
    EXISTS (
        SELECT 1
        FROM public.profiles
        WHERE profiles.id = auth.uid()
        AND profiles.role IN ('admin', 'teacher')
    )
);


-- ============================================================
-- 18. DATABASE TEST
-- ============================================================

SELECT
    'profiles' AS table_name,
    COUNT(*) AS row_count
FROM public.profiles

UNION ALL

SELECT
    'curriculum_chunks',
    COUNT(*)
FROM public.curriculum_chunks

UNION ALL

SELECT
    'tutor_sessions',
    COUNT(*)
FROM public.tutor_sessions

UNION ALL

SELECT
    'tutor_messages',
    COUNT(*)
FROM public.tutor_messages

UNION ALL

SELECT
    'exams',
    COUNT(*)
FROM public.exams

UNION ALL

SELECT
    'exam_attempts',
    COUNT(*)
FROM public.exam_attempts;