-- Enable Vector extension for pgvector
create extension if not exists vector;

-- Create Profiles table linking to auth.users
create table public.profiles (
  id uuid references auth.users on delete cascade primary key,
  name text not null,
  role text not null check (role in ('student', 'teacher', 'admin')),
  grade text,
  language text not null default 'English',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS)
alter table public.profiles enable row level security;

create policy "Allow public read-access to profiles"
  on public.profiles for select
  using (true);

create policy "Allow users to update their own profile"
  on public.profiles for update
  using (auth.uid() = id);

-- Trigger to automatically create a profile row when a user signs up
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, name, role, grade, language)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'name', 'New User'),
    coalesce(new.raw_user_meta_data->>'role', 'student'),
    new.raw_user_meta_data->>'grade',
    coalesce(new.raw_user_meta_data->>'language', 'English')
  );
  return new;
end;
$$ language plpgsql security definer;

create or replace trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- Create Curriculum Chunks table for RAG
create table public.curriculum_chunks (
  id bigint generated by default as identity primary key,
  subject text not null,
  topic text not null,
  grade text not null,
  language text not null,
  source_document text not null,
  content text not null,
  embedding vector(1536),
  version int not null default 1,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.curriculum_chunks enable row level security;

create policy "Allow read access to curriculum chunks for authenticated users"
  on public.curriculum_chunks for select
  to authenticated
  using (true);

create policy "Allow insert/update/delete for admins and teachers"
  on public.curriculum_chunks for all
  to authenticated
  using (
    exists (
      select 1 from public.profiles
      where profiles.id = auth.uid()
        and profiles.role in ('admin', 'teacher')
    )
  );

-- Create Cosine Similarity search function for RAG retrieval
create or replace function public.match_chunks (
  query_embedding vector(1536),
  match_threshold float,
  match_count int,
  filter_subject text,
  filter_grade text,
  filter_language text
) returns table (
  id bigint,
  subject text,
  topic text,
  grade text,
  language text,
  source_document text,
  content text,
  similarity float
)
language plpgsql
as $$
begin
  return query
  select
    cc.id,
    cc.subject,
    cc.topic,
    cc.grade,
    cc.language,
    cc.source_document,
    cc.content,
    1 - (cc.embedding <=> query_embedding) as similarity
  from public.curriculum_chunks cc
  where cc.subject = filter_subject
    and cc.grade = filter_grade
    and cc.language = filter_language
    and 1 - (cc.embedding <=> query_embedding) > match_threshold
  order by cc.embedding <=> query_embedding
  limit match_count;
end;
$$;

-- Create Tutor Sessions table
create table public.tutor_sessions (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete cascade not null,
  subject text not null,
  started_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.tutor_sessions enable row level security;

create policy "Users can manage their own tutor sessions"
  on public.tutor_sessions for all
  to authenticated
  using (auth.uid() = user_id);

-- Create Tutor Messages table
create table public.tutor_messages (
  id bigint generated by default as identity primary key,
  session_id bigint references public.tutor_sessions on delete cascade not null,
  sender text not null check (sender in ('student', 'tutor')),
  content text not null,
  timestamp timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.tutor_messages enable row level security;

create policy "Users can manage messages in their own sessions"
  on public.tutor_messages for all
  to authenticated
  using (
    exists (
      select 1 from public.tutor_sessions
      where tutor_sessions.id = session_id
        and tutor_sessions.user_id = auth.uid()
    )
  );

-- Create Exams table
create table public.exams (
  id bigint generated by default as identity primary key,
  subject text not null,
  topic text not null,
  difficulty text not null,
  grade text not null,
  created_by uuid references auth.users on delete set null,
  questions jsonb not null,
  answer_key jsonb not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.exams enable row level security;

create policy "Allow read access to exams for authenticated users"
  on public.exams for select
  to authenticated
  using (true);

create policy "Allow teachers/admins to create/update exams"
  on public.exams for all
  to authenticated
  using (
    exists (
      select 1 from public.profiles
      where profiles.id = auth.uid()
        and profiles.role in ('admin', 'teacher')
    )
  );

-- Create Exam Attempts table
create table public.exam_attempts (
  id bigint generated by default as identity primary key,
  exam_id bigint references public.exams on delete cascade not null,
  student_id uuid references auth.users on delete cascade not null,
  answers jsonb not null,
  score float not null,
  submitted_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.exam_attempts enable row level security;

create policy "Users can manage their own exam attempts"
  on public.exam_attempts for all
  to authenticated
  using (auth.uid() = student_id);

create policy "Teachers can read all exam attempts"
  on public.exam_attempts for select
  to authenticated
  using (
    exists (
      select 1 from public.profiles
      where profiles.id = auth.uid()
        and profiles.role in ('admin', 'teacher')
    )
  );
