-- ============================================================
-- I-Pass-A — Full Database Schema
-- Run this in Supabase SQL Editor (reset / fresh deploy)
-- ============================================================

-- Enable Vector extension for pgvector
create extension if not exists vector;

-- ============================================================
-- PROFILES
-- ============================================================
create table public.profiles (
  id            uuid references auth.users on delete cascade primary key,
  name          text not null,
  role          text not null check (role in ('student', 'teacher', 'admin')),
  grade         text,                    -- student's current grade (6, 8, 12)
  grade_taught  text,                    -- teacher's assigned grade (6, 8, 12)
  language      text not null default 'English',
  created_at    timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.profiles enable row level security;

create policy "Allow public read-access to profiles"
  on public.profiles for select
  using (true);

create policy "Allow users to update their own profile"
  on public.profiles for update
  using (auth.uid() = id);

-- Auto-create profile on signup
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, name, role, grade, grade_taught, language)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'name', 'New User'),
    coalesce(new.raw_user_meta_data->>'role', 'student'),
    new.raw_user_meta_data->>'grade',
    new.raw_user_meta_data->>'grade_taught',
    coalesce(new.raw_user_meta_data->>'language', 'English')
  );
  return new;
end;
$$ language plpgsql security definer;

create or replace trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- ============================================================
-- CURRICULUM CHUNKS  (RAG vector store — admin upload only)
-- ============================================================
create table public.curriculum_chunks (
  id              bigint generated by default as identity primary key,
  subject         text not null,
  topic           text not null,
  grade           text not null,
  language        text not null,
  source_document text not null,
  content         text not null,
  embedding       vector(1536),
  version         int not null default 1,
  uploaded_by     text default 'System',
  created_at      timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.curriculum_chunks enable row level security;

create policy "Allow read access to curriculum chunks for authenticated users"
  on public.curriculum_chunks for select
  to authenticated
  using (true);

-- Only admins can insert/update/delete curriculum chunks
create policy "Allow insert/update/delete for admins only"
  on public.curriculum_chunks for all
  to authenticated
  using (
    exists (
      select 1 from public.profiles
      where profiles.id = auth.uid()
        and profiles.role = 'admin'
    )
  );

-- Cosine-similarity RAG retrieval function
create or replace function public.match_chunks (
  query_embedding  vector(1536),
  match_threshold  float,
  match_count      int,
  filter_subject   text,
  filter_grade     text,
  filter_language  text
) returns table (
  id              bigint,
  subject         text,
  topic           text,
  grade           text,
  language        text,
  source_document text,
  content         text,
  similarity      float
)
language plpgsql
as $$
begin
  return query
  select
    cc.id,
    cc.subject,
    cc.topic,
    cc.grade,
    cc.language,
    cc.source_document,
    cc.content,
    1 - (cc.embedding <=> query_embedding) as similarity
  from public.curriculum_chunks cc
  where cc.subject       = filter_subject
    and cc.grade         = filter_grade
    and cc.language      = filter_language
    and 1 - (cc.embedding <=> query_embedding) > match_threshold
  order by cc.embedding <=> query_embedding
  limit match_count;
end;
$$;

-- ============================================================
-- TUTOR SESSIONS
-- ============================================================
create table public.tutor_sessions (
  id         bigint generated by default as identity primary key,
  user_id    uuid references auth.users on delete cascade not null,
  subject    text not null,
  started_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.tutor_sessions enable row level security;

create policy "Users can manage their own tutor sessions"
  on public.tutor_sessions for all
  to authenticated
  using (auth.uid() = user_id);

-- ============================================================
-- TUTOR MESSAGES  (includes sources + out_of_scope for history)
-- ============================================================
create table public.tutor_messages (
  id           bigint generated by default as identity primary key,
  session_id   bigint references public.tutor_sessions on delete cascade not null,
  sender       text not null check (sender in ('student', 'tutor')),
  content      text not null,
  sources      jsonb,          -- [{source, content, similarity}] for tutor messages
  out_of_scope boolean default false,
  timestamp    timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.tutor_messages enable row level security;

create policy "Users can manage messages in their own sessions"
  on public.tutor_messages for all
  to authenticated
  using (
    exists (
      select 1 from public.tutor_sessions
      where tutor_sessions.id = session_id
        and tutor_sessions.user_id = auth.uid()
    )
  );

-- ============================================================
-- EXAMS  (AI-generated practice exams)
-- ============================================================
create table public.exams (
  id           bigint generated by default as identity primary key,
  subject      text not null,
  topic        text not null,
  difficulty   text not null,
  grade        text not null,
  created_by   uuid references auth.users on delete set null,
  questions    jsonb not null,
  answer_key   jsonb not null,
  created_at   timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.exams enable row level security;

create policy "Allow read access to exams for authenticated users"
  on public.exams for select
  to authenticated
  using (true);

create policy "Allow teachers and admins to create exams"
  on public.exams for insert
  to authenticated
  with check (
    exists (
      select 1 from public.profiles
      where profiles.id = auth.uid()
        and profiles.role in ('admin', 'teacher', 'student')
    )
  );

create policy "Allow creator to update/delete their exams"
  on public.exams for update
  to authenticated
  using (auth.uid() = created_by);

create policy "Allow admins to manage all exams"
  on public.exams for all
  to authenticated
  using (
    exists (
      select 1 from public.profiles
      where profiles.id = auth.uid()
        and profiles.role = 'admin'
    )
  );

-- ============================================================
-- EXAM ATTEMPTS  (student self-practice attempts)
-- ============================================================
create table public.exam_attempts (
  id           bigint generated by default as identity primary key,
  exam_id      bigint references public.exams on delete cascade not null,
  student_id   uuid references auth.users on delete cascade not null,
  answers      jsonb not null,
  score        float not null,
  submitted_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.exam_attempts enable row level security;

create policy "Students can manage their own exam attempts"
  on public.exam_attempts for all
  to authenticated
  using (auth.uid() = student_id);

create policy "Teachers and admins can read all exam attempts"
  on public.exam_attempts for select
  to authenticated
  using (
    exists (
      select 1 from public.profiles
      where profiles.id = auth.uid()
        and profiles.role in ('admin', 'teacher')
    )
  );

-- ============================================================
-- TEACHER ASSIGNMENTS  (teacher publishes exam to a grade)
-- ============================================================
create table public.teacher_assignments (
  id             bigint generated by default as identity primary key,
  exam_id        bigint references public.exams on delete cascade not null,
  teacher_id     uuid references auth.users on delete cascade not null,
  title          text not null,
  assignment_type text not null check (assignment_type in ('quiz', 'homework', 'assignment')),
  target_grade   text not null,           -- which grade this is assigned to
  due_date       timestamp with time zone not null,
  published      boolean not null default false,
  published_at   timestamp with time zone,
  created_at     timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.teacher_assignments enable row level security;

-- Teachers see their own assignments; students see published assignments for their grade
create policy "Teachers can manage their own assignments"
  on public.teacher_assignments for all
  to authenticated
  using (auth.uid() = teacher_id);

create policy "Students can view published assignments for their grade"
  on public.teacher_assignments for select
  to authenticated
  using (
    published = true
    and exists (
      select 1 from public.profiles
      where profiles.id = auth.uid()
        and profiles.grade = target_grade
        and profiles.role = 'student'
    )
  );

create policy "Admins can manage all assignments"
  on public.teacher_assignments for all
  to authenticated
  using (
    exists (
      select 1 from public.profiles
      where profiles.id = auth.uid()
        and profiles.role = 'admin'
    )
  );

-- ============================================================
-- ASSIGNMENT SUBMISSIONS  (student submits a teacher assignment)
-- ============================================================
create table public.assignment_submissions (
  id              bigint generated by default as identity primary key,
  assignment_id   bigint references public.teacher_assignments on delete cascade not null,
  exam_id         bigint references public.exams on delete cascade not null,
  student_id      uuid references auth.users on delete cascade not null,
  answers         jsonb not null,
  raw_score       float,                  -- auto-scored percentage (for MC/TF)
  teacher_score   float,                  -- manually set by teacher after review
  teacher_feedback text,
  graded          boolean not null default false,
  submitted_at    timestamp with time zone default timezone('utc'::text, now()) not null,
  graded_at       timestamp with time zone
);

alter table public.assignment_submissions enable row level security;

-- Students can submit and view their own submissions
create policy "Students can manage their own submissions"
  on public.assignment_submissions for all
  to authenticated
  using (auth.uid() = student_id);

-- Teachers can read and update (grade) submissions for their assignments
create policy "Teachers can read and grade submissions for their assignments"
  on public.assignment_submissions for all
  to authenticated
  using (
    exists (
      select 1 from public.teacher_assignments ta
      where ta.id = assignment_id
        and ta.teacher_id = auth.uid()
    )
  );

create policy "Admins can manage all submissions"
  on public.assignment_submissions for all
  to authenticated
  using (
    exists (
      select 1 from public.profiles
      where profiles.id = auth.uid()
        and profiles.role = 'admin'
    )
  );
